version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app

  frontend:
    build: ../MVP-PUC-FRONT-PRINCIPAL
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
